#We can create instance with ansible also but its not good to go with ansible as ansible is natively for configuration management not for infra set up and ansible cant deal as smooth as terraform do.

- name: Create instance
  hosts: localhost
  tasks:
    - name: Create Instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: ami-0a017d8ceb274537d
